- packages/go-kosu/package.json
- packages/go-kosu/rpc/service.go
Fix the Order stream subscription (`newOrders`) to stop publishing the events by listening on new blocks instead of Tx and adding an intermediary buffer.
Fixes #253
> go-kosu: RPC Orders stream bug workaround

- packages/go-kosu/Makefile
After import path change (`go-kosu/...` => `github.com/ParadigmFoundation/kosu-monorepo/packages/go-kosu/...`) Makefile needed to be updated as well so Version and Git Commit get set properly.
> go-kosu: update makefile with import path change

- packages/go-kosu/rpc/service.go
When a resource has not been created yet and queried through RPC we get a NotFoundError which can be confusing.
This mask that particular error
> go-kosu: mask ErrNotFound on RPC requests

- packages/go-kosu/abci/app.go
- packages/go-kosu/abci/order_test.go
Use MaxOrderBytes as a size limit to incoming Order TXs.
If the value is zero, the check is skipped.
This value SHOULD be specified in the genesis's `app_state` field
> go-kosu: use MaxOrderBytes in CheckTx

- packages/order-server/src/db.ts
- packages/order-server/src/routes/search.ts
- packages/order-server/src/utils.ts
The method used to render quote snapshots was detecting `bid` vs `ask` to determine the base an quote assets to generate the price, which was incorrect.
The price is based off weather the maker asset or the taker asset is the base asset, not what the side is.
> order-server: fix price quote error on /search endpoint

- packages/go-kosu/CHANGELOG.md
- packages/go-kosu/Makefile
- packages/go-kosu/abci/app_test.go
- packages/go-kosu/abci/genesis.go
- packages/go-kosu/abci/validators.go
- packages/go-kosu/abci/validators_test.go
- packages/go-kosu/cmd/kosud/main.go
- packages/go-kosu/witness/eth.go
Introduce SnapshotBlock support into the Ethereum Witness and genesis block.
> go-kosu: ethereum snapshot block

- packages/go-kosu/CHANGELOG.md
- packages/go-kosu/witness/witness.go
We are using `append()` instead of `append()...` when logging the fields.
The logger expect something different that an array as a valid key, now we're expanding the array when passing it to the logging function
> Fix witness unsupported key logger

- packages/go-kosu/CHANGELOG.md
- packages/go-kosu/abci/app.go
- packages/go-kosu/abci/app_test.go
- packages/go-kosu/abci/genesis.go
- packages/go-kosu/abci/types/types.go
InitialPosters are defined like this:
```json
{
"initial_validator_info": [],
"snapshot_block": 999,
"initial_posters": {
"some_address": {
"balance": "1234", "limit": 10
}
}
```
As the balance is a BigNum is represented as a string in the JSON.
> go-kosu: Add InitialPosters support

- packages/kosu-genesis-cli/src/functions.ts
- packages/kosu-genesis-cli/src/types.d.ts
- packages/kosu-genesis-cli/test/snapshot_test.ts
- packages/kosu-genesis-cli/test/unit_test.ts
Tendermint requires initial power to be set, even though it gets overidden by go-kosu. 
- The convention is that snapshot validators all set `power` as `"1"`
- Changed `SnapshotPoster` key `address` to `ethereum_address` (as expected by client)
> genesis-cli: set snapshot power to 1

- packages/go-kosu/CHANGELOG.md
- packages/go-kosu/abci/app_test.go
- packages/go-kosu/abci/validators.go
It requires power = 1 when `initial_validator_info` is defined.
> go-kosu: Require power=1 in genesis file

- packages/go-kosu/CHANGELOG.md
- packages/go-kosu/abci/app.go
- packages/go-kosu/abci/client.go
- packages/go-kosu/abci/lite.go
- packages/go-kosu/cmd/kosu-cli/main.go
- packages/go-kosu/cmd/kosulite/main.go
- packages/go-kosu/go.mod
- packages/go-kosu/rpc/service.go
- packages/go-kosu/tests/witness_test.go
This implements a basic Lite Client. The LiteClient is implemented as a RPC Client (`./abci/lite.go`) and also as a Proxy sub-command (`./cmd/kosulite/`) so that `./kosu-cli` can use the lite client proxy as an endpoint.
This PR also includes fixes a `./kosu-cli` bug and it restructures the Query Path adding the `./store/` prefix, this change was required to make the lite client works.
> Feature/go kosu/lite client

- packages/kosu-genesis-cli/src/cli/cli.ts
- packages/kosu-genesis-cli/src/cli/utils.ts
- packages/kosu-genesis-cli/src/types.d.ts
Adding orders buffer size consensus parameter to genesis cli to keep in line with `go-kosu` (see #321).
> kosu-genesis-cli: add orders limit consensus parameter

- .drone.jsonnet
- .drone.yml
We must `git checkout .` to remove the auto-generated `bindata.go` file after `yarn build`.
> fix drone release step (re-add git checkout)

- cloudbuild/main.yaml
An update to the docs deploy steps got left out of #335 (due to `kosu.js` => `kosu-contract-helpers` rename).
> cloudbuild: update path name for copy step

- packages/go-kosu/CHANGELOG.md
- packages/go-kosu/service/service.go
The `--laddr` where used as the rpc target, that makes sense when running in fullnode mode, so that the RPC API will connect to it. But in lite mode, we should connect to the fullnode, before this PR we were using `--laddr` for both modes.
This PR updates that behavior.
Closes #330
> go-kosu: Fix wrong RPC remote address in lite mode

- packages/dev-images/README.md
- packages/dev-images/ci/go-kosu.Dockerfile
- packages/dev-images/ci/node.Dockerfile
- packages/dev-images/docs/README.md
[Our Google Cloud builds have been failing](https://console.cloud.google.com/cloud-build/builds/1500cf3c-3378-4b2d-825b-595630c4ccfe?project=kosu-io&organizationId=401452478378) due to issues with the Dockerfile steps that install `go-ethereum` binaries ultimately related to the `GOPATH` and go modules from 1.11. I'm not sure why it arose recently, since we've been on go >1.11 for a while).
A new method that handles lack of GO111MODULE support for `go-ethereum` should fix this issue. All builds for geth are done from `/home/go/github.com/ethereum/go-ethereum`, since apparently they don't support go modules.
> dev-images: fixing broken go-ethereum installs

- packages/go-kosu/CHANGELOG.md
- packages/go-kosu/package.json
once this is merged I'll push `:v0.5.0` tag
> go-kosu: bump version v0.5.0

- packages/dev-images/ci/go-kosu.Dockerfile
- packages/dev-images/ci/node.Dockerfile
- Fixing a `golangci-lint` install issue in `go-kosu-ci`
- Downgrade from Node.js 12 LTS to Node.js 10 LTS for better compatibility
> dev-images: update golang and node.js CI images

- packages/kosu-node-client/docs/README.md
- packages/kosu-node-client/docs/classes/nodeclient.md
- packages/kosu-node-client/docs/globals.md
- packages/kosu-node-client/src/index.ts
- packages/kosu-node-client/src/node_client.ts
- Removes an extra parsing step from Validator and Poster queries that was an artifact of a bug from `go-kosu` protobuf serialization pre-0.4.
- Exports relevant types from @kosu/types
- Update a filename
- Regenerate documentation
> node-client: undo serialization hack from client bug

- packages/kosu-test-helpers/src/index.ts
For some reason, with the new linter rules, we get the following errors from `test-helpers`:
```
ERROR: /Users/hen/GitHub/km/packages/kosu-test-helpers/src/index.ts:341:31 - Operands of '+' operation must either be both strings or both numbers or both bigints, but found any + 1
ERROR: /Users/hen/GitHub/km/packages/kosu-test-helpers/src/index.ts:342:27 - Operands of '+' operation must either be both strings or both numbers or both bigints, but found any + number
ERROR: /Users/hen/GitHub/km/packages/kosu-test-helpers/src/index.ts:343:27 - Operands of '+' operation must either be both strings or both numbers or both bigints, but found any + number
```
The lines in question are fine, but for some reason the type detected for `base` is not being used by the linter. We should address this and …
> test-helpers: disable linter for specific lines

- packages/kosu-node-client/package.json
Bump `@kosu/node-client` to `v0.5.0`
From now on, the version of `@kosu/node-client` should line up with the version of `@kosu/go-kosu` to ensure and indicate compatibility.
> node-client: release v0.5.0

- packages/go-kosu/CHANGELOG.md
- packages/go-kosu/abci/cli/abci.go
- packages/go-kosu/abci/cli/cli.go
- packages/go-kosu/cmd/kosud/main.go
- packages/go-kosu/service/service.go
At this point it's still tricky to implement the --validator flag here.
This will create a circular dependency between the Witness and the ABCI
server, the witness needs the ABCI server to be started to query rounds, which is
implemented by tendermint and not go-kosu anymore.
There are possible solutions to this problem that I'd explore later.
For now, this is working, and you can alternate, running as a
stand-alone application and then switch to ABCI mode using the same
homedir.
This has been tested in our `micro` instance as follows:
In one terminal run
```
kosud abci
```
While it's running run in another terminal
```
tendermint --home ~/.home/kosu node
```
While `kosud abci` will log the `app` module, `tendermint node` will log `consensus` and `state` modules.
> go-kosu: Add `abci` subcommmand

- packages/kosu-genesis-cli/package.json
- packages/kosu-genesis-cli/src/cli/cli.ts
- yarn.lock
- Removing un-used dependencies in anticipation of `go-kosu` v0.6 and genesis-cli v0.6
> genesis-cli: dependency cleanup

- packages/kosu-solidity-tests/test/validator_registry.ts
- packages/kosu-system-contracts/contracts/validator/ValidatorRegistry.sol
- packages/kosu-test-helpers/src/index.ts
- packages/kosu-wrapper-enhancements/src/ValidatorRegistry.ts
- packages/kosu-wrapper-enhancements/test/validator_registry_test.ts
The current `ValidatorRegistry` implementation allows listing applicants to specify a `stake` that must be greater than or equal to a `minimumBalance` (currently specified as `500 ether` units of KOSU ).
This `minimumBalance`, as well as any number of tokens included above this amount are available to be slashed in the event of a successful challenge, and is used to set the validator's vote power (if accepted) on the Kosu network.
The power is calculated as `floor(stake / 1e18)` so the "unit" amount of Kosu is used to set vote power, as opposed to the "base unit" amount.
_Parameter names not final._
This proposal introduces two "top-level" changes. First, it introduces a new parameter, `slashableProportion` that is the fraction of a listings stake that is available to slashing in the case …
> Updates to validator slashable stake implementation
