- packages/go-kosu/CHANGELOG.md
- packages/go-kosu/abci/app.go
- packages/go-kosu/abci/types/crypto.go
- packages/go-kosu/abci/types/types.go
Verify that Rebalance and Witness tx are submitted by a validator.
This is only checked in `CheckTx`.
Also a CHANGELOG.md file has been added to keep track of changes belonging to a release.
> Bug/go kosu/validator txs only

- packages/go-kosu/CHANGELOG.md
Keep changelog up to date with the latest changes.
> go-kosu: update CHANGELOG.md

- .drone.jsonnet
- .drone.yml
> Adding tag to ci

- packages/dev-images/ci/node.Dockerfile
> adding npm library to image.

- packages/kosu-docs/package.json
- yarn.lock
> removing simple spinner

- packages/kosu-docs/docs/.vuepress/theme/Layout.vue
- packages/kosu-docs/package.json
- yarn.lock
Added the spinner component to dependencies as well as fixed the compile issue.
> kosu-docs: added spinner and fixed compile error

- packages/kosu-docs/docs/.vuepress/theme/Navbar.vue
- packages/kosu-docs/docs/.vuepress/theme/Page.vue
fixed a color disparity between the sidebar and logo background
> kosu-docs: fixing sidebar color inconsistency

- cloudbuild/main.yaml
- packages/kosu-docs/docs/kosu-genesis-cli/README.md
- packages/kosu-docs/docs/kosu-genesis-cli/classes/eventemitter.md
- packages/kosu-docs/docs/kosu-genesis-cli/classes/kosu.md
- packages/kosu-docs/docs/kosu-genesis-cli/classes/kosutoken.md
- packages/kosu-docs/docs/kosu-genesis-cli/classes/nodeclient.md
- packages/kosu-docs/docs/kosu-genesis-cli/classes/ordergateway.md
- packages/kosu-docs/docs/kosu-genesis-cli/classes/orderhelper.md
- packages/kosu-docs/docs/kosu-genesis-cli/classes/posterregistry.md
- packages/kosu-docs/docs/kosu-genesis-cli/classes/treasury.md
- packages/kosu-docs/docs/kosu-genesis-cli/classes/validatorregistry.md
- packages/kosu-docs/docs/kosu-genesis-cli/classes/voting.md
- packages/kosu-docs/docs/kosu-genesis-cli/globals.md
- packages/kosu-docs/docs/kosu-genesis-cli/interfaces/decodedkosulogargs.md
- packages/kosu-docs/docs/kosu-genesis-cli/interfaces/kosuoptions.md
- packages/kosu-docs/docs/kosu-genesis-cli/interfaces/kosuutils.md
- packages/kosu-docs/docs/kosu-genesis-cli/interfaces/logwithdecodedkosuargs.md
- packages/kosu-docs/docs/kosu-genesis-cli/interfaces/order.md
- packages/kosu-docs/docs/kosu-genesis-cli/interfaces/orderargument.md
- packages/kosu-docs/docs/kosu-genesis-cli/interfaces/orderrejectioninfo.md
- packages/kosu-docs/docs/kosu-genesis-cli/interfaces/ordervalidationresult.md
- packages/kosu-docs/docs/kosu-genesis-cli/interfaces/postableorder.md
- packages/kosu-docs/docs/kosu-genesis-cli/interfaces/poster.md
- packages/kosu-docs/docs/kosu-genesis-cli/interfaces/roundinfo.md
- packages/kosu-docs/docs/kosu-genesis-cli/interfaces/takeableorder.md
- packages/kosu-docs/docs/kosu-genesis-cli/interfaces/validator.md
#280 broke the CD build for bad .yaml syntax, this fixes it.
> cloudbuild: fix syntax error in main build

- packages/kosu-docs/docs/overview/validator-curation.md
> kosu-docs: changing validator process diagram link

- packages/go-kosu/CHANGELOG.md
- packages/go-kosu/abci/types/types.go
- packages/go-kosu/abci/types/types_test.go
> go-kosu: Fix BigInt JSON Serialization

- packages/go-kosu/CHANGELOG.md
- packages/go-kosu/docs/kosu_rpc.md
- packages/go-kosu/rpc/rpc_test.go
- packages/go-kosu/rpc/service.go
> go-kosu: Add GetBlocks RPC endpoint

- packages/kosu-deployed-addresses/package.json
- packages/kosu-deployed-addresses/src/index.ts
- packages/kosu-migrations/src/index.ts
- packages/kosu-types/src/index.ts
-   [ ] Tag issue (bug, enhancement, feature, etc.)
-   [ ] Initial discussion/assign team member
-   [ ] Move discussion to PR if necessary and when ready
> [deployed-addresses] Add function(s) to expose the data by network id.

- README.md
- packages/dev-images/ci/go-kosu.Dockerfile
- packages/dev-images/ci/node.Dockerfile
- packages/go-kosu/Dockerfile
- packages/go-kosu/Dockerfile.compose
- packages/go-kosu/README.md
- packages/go-kosu/docs/README.md
- packages/go-kosu/docs/usage.md
- packages/go-kosu/go.mod
- packages/kosu-docs/docs/go-kosu/README.md
- packages/kosu-docs/docs/go-kosu/usage.md
> Bump go version to 1.13

- packages/kosu-test-helpers/src/index.ts
- Fixing issues arising with new linter config
> test-helpers: address linter issues

- packages/kosu-types/package.json
- yarn.lock
Bump `@kosu/types` to `v0.3.1`
> types: release v0.3.1

- packages/kosu-docs/docs/.vuepress/config.js
> Adding doc vuepress config that reads docs in directory

- packages/kosu-docs/docs/.vuepress/config.js
> Adding interfaces check for folder.

- packages/kosu-docs/docs/overview/validator-application.md
> docs: update links to class docs

- packages/kosu-system-contracts/contracts/validator/ValidatorRegistry.sol
> Fixing poor comment and naming.

- packages/kosu-contract-helpers/test/order_helper_test.js
- packages/kosu-geth/genesis-kosu-test.json
- packages/kosu-geth/genesis-kosu.json
- packages/kosu-geth/kosu-test.Dockerfile
- packages/kosu-geth/kosu.Dockerfile
- packages/kosu-migrations/src/migrations.ts
- packages/kosu-solidity-tests/test/validator_registry.ts
> Updating genesis config and geth versions
